name: edward_cpu_tf2.0
channels:
  # - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyterlab
  - tqdm
  - matplotlib
  - numpy=1.15.4
  - pandas
  - pillow
  - pydot
  - scikit-learn
  - scikit-image
#  - tensorflow
  - geopandas
  - rasterio
  - pip:
      - tensorflow==2.0.0-alpha0
      - edward
      - sentinelhub
      - gputil
