name: edward
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyterlab
  - tqdm
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pydot
  - scikit-image
  - keras
  - tensorflow
  - geopandas
  - rasterio
  - pip:
    - edward
    - sentinelhub
