name: edward
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyterlab
  - tqdm
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pydot
  - scikit-image
  - keras-gpu
  - tensorflow-gpu
  - cudatoolkit=9.0
  - geopandas
  - rasterio
  - pip:
    - edward
    - sentinelhub
    - gpustat
# prefix: /u/44/prollm1/unix/.conda/envs/edward
