name: edward_cpu_tf2.0
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyterlab
  - tqdm
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pydot
  - scikit-image
  - scikit-learn
#  - tensorflow-gpu
  - cudatoolkit=10.0
  - cudnn #???
  - geopandas
  - rasterio
  - pip:
    - tensorflow-gpu==2.0.0-alpha0
    - sentinelhub
    - gpustat
    - gputil
    - edward
