name: edward
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyterlab
  - tqdm
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pydot
  - scikit-image
  - tensorflow-gpu
  - cudatoolkit=9.0
  - scikit-learn
  - geopandas
  - rasterio
  - pip:
    - edward
    - sentinelhub
    - gpustat
    - gputil
